"use client";
import {useEffect,useRef,useState} from "react";
type Unit={id:number;x:number;y:number;tx:number;ty:number;team:"player"|"enemy";kind:"rider"|"spearman"|"archer";hp:number};
const army:Unit[]=[{id:1,x:190,y:390,tx:190,ty:390,team:"player",kind:"rider",hp:100},{id:2,x:225,y:420,tx:225,ty:420,team:"player",kind:"spearman",hp:100},{id:3,x:160,y:430,tx:160,ty:430,team:"player",kind:"archer",hp:100},{id:11,x:735,y:185,tx:735,ty:185,team:"enemy",kind:"rider",hp:100},{id:12,x:770,y:220,tx:770,ty:220,team:"enemy",kind:"spearman",hp:100},{id:13,x:710,y:235,tx:710,ty:235,team:"enemy",kind:"archer",hp:100}];
export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null),units=useRef<Unit[]>(army),selRef=useRef<number[]>([]);
 const[screen,setScreen]=useState<"login"|"lobby"|"game">("login"),[name,setName]=useState(""),[room,setRoom]=useState("SYRIA-378"),[food,setFood]=useState(510),[gold,setGold]=useState(260),[pop,setPop]=useState(3),[selected,setSelected]=useState<number[]>([]),[message,setMessage]=useState("Select warriors, then click the terrain to move.");
 useEffect(()=>{selRef.current=selected},[selected]);
 useEffect(()=>{if(screen!=="game")return;const c=canvasRef.current!,ctx=c.getContext("2d")!;let frame=0,raf=0;const draw=()=>{frame++;const g=ctx.createLinearGradient(0,0,960,640);g.addColorStop(0,"#b28a52");g.addColorStop(.55,"#82623d");g.addColorStop(1,"#35402e");ctx.fillStyle=g;ctx.fillRect(0,0,960,640);ctx.fillStyle="#243f36";ctx.beginPath();ctx.moveTo(0,570);ctx.bezierCurveTo(210,490,340,610,530,525);ctx.bezierCurveTo(720,440,850,520,960,450);ctx.lineTo(960,640);ctx.lineTo(0,640);ctx.fill();ctx.strokeStyle="#c8aa72";ctx.lineWidth=52;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(100,555);ctx.bezierCurveTo(300,470,450,500,570,360);ctx.bezierCurveTo(650,270,730,290,870,110);ctx.stroke();for(let i=0;i<34;i++){const x=(i*83+45)%960,y=(i*127+80)%500,r=10+(i%5)*3;ctx.fillStyle=i%2?"#66503a":"#7c6041";ctx.beginPath();ctx.ellipse(x,y,r,r*.65,-.4,0,7);ctx.fill()}fort(ctx,125,365,"#274e52");fort(ctx,825,140,"#862e28");for(let i=0;i<10;i++)tree(ctx,75+(i%5)*28,220+Math.floor(i/5)*32);for(let i=0;i<8;i++)tree(ctx,770+(i%4)*27,355+Math.floor(i/4)*32);ctx.fillStyle="#d3af43";for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(450+(i%3)*17,165+Math.floor(i/3)*14,7,0,7);ctx.fill()}units.current.forEach(u=>{const dx=u.tx-u.x,dy=u.ty-u.y,d=Math.hypot(dx,dy);if(d>2){u.x+=dx/d*1.15;u.y+=dy/d*1.15}});units.current.forEach(u=>{const foe=units.current.find(v=>v.team!==u.team&&Math.hypot(v.x-u.x,v.y-u.y)<30);if(foe&&frame%25===0)foe.hp-=7});units.current=units.current.filter(u=>u.hp>0);units.current.forEach(u=>warrior(ctx,u,selRef.current.includes(u.id)));ctx.fillStyle="#111b18dd";ctx.fillRect(788,494,155,125);ctx.strokeStyle="#d0b47a";ctx.strokeRect(788,494,155,125);units.current.forEach(u=>{ctx.fillStyle=u.team==="player"?"#55cbd0":"#e65a4f";ctx.fillRect(788+u.x/960*155-2,494+u.y/640*125-2,5,5)});raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[screen]);
 const click=(e:React.MouseEvent<HTMLCanvasElement>)=>{const c=e.currentTarget,r=c.getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*640/r.height,hit=units.current.find(u=>u.team==="player"&&Math.hypot(u.x-x,u.y-y)<22);if(hit){const n=e.shiftKey?[...new Set([...selected,hit.id])]:[hit.id];setSelected(n);setMessage(`${hit.kind} selected. Click a destination.`)}else if(selected.length){units.current.forEach(u=>{if(selected.includes(u.id)){u.tx=x+(u.id%3)*15;u.ty=y+(u.id%2)*12}});setMessage("Warriors moving to your command.")}};
 const train=(kind:Unit["kind"])=>{if(food<80||gold<40){setMessage("Not enough food or gold.");return}setFood(v=>v-80);setGold(v=>v-40);const id=Date.now();units.current.push({id,x:135,y:375,tx:180+Math.random()*50,ty:400+Math.random()*40,team:"player",kind,hp:100});setPop(v=>v+1);setMessage(`${kind} trained at the desert camp.`)};
 return <main className="shell"><header><div className="brand"><span className="sigil">M</span><div><b>MAWIYYA</b><small>DESERT CROWN</small></div></div><div className="online"><i/>1,248 COMMANDERS ONLINE</div></header>
 {screen==="login"&&<section className="gate"><div className="portrait"><img src="/mawiyya.png" alt="Queen Mawiyya holding a spear"/><div className="portraitText"><span>378 CE · TANUKHID CONFEDERATION</span><h1>THE DESERT<br/>REMEMBERS</h1><p>Command Queen Mawiyya’s riders across the Syrian frontier. Build your camp. Rally the tribes. Break the imperial line.</p></div></div><form onSubmit={e=>{e.preventDefault();if(name.trim())setScreen("lobby")}}><p className="eyebrow">COMMANDER ACCESS</p><h2>Enter the frontier</h2><label>COMMANDER NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required/></label><label>REGION<select><option>Europe · West</option><option>Middle East</option><option>North America</option></select></label><button>ENTER WAR ROOM</button><small>Prototype lobby · no password required</small></form></section>}
 {screen==="lobby"&&<section className="lobby"><div><p className="eyebrow">MULTIPLAYER SKIRMISH</p><h1>Choose your battlefield</h1><div className="mapCard"><div className="mapArt"><span>SYRIAN FRONTIER</span></div><div><h3>The Orontes Crossing</h3><p>2 players · Temperate desert · Standard resources</p><ul><li>Oasis trade route</li><li>Two fortified starting camps</li><li>Mountain choke points</li></ul></div></div></div><aside><span className="status">ROOM READY</span><h2>{room}</h2><div className="slot"><b>01</b><span>{name}<small>MAWIYYA · TANUKHIDS</small></span><i>READY</i></div><div className="slot enemy"><b>02</b><span>Imperial Eagle<small>ROMAN FOEDERATI · AI</small></span><i>HARD</i></div><label>ROOM CODE<input value={room} onChange={e=>setRoom(e.target.value.toUpperCase())}/></label><button onClick={()=>setScreen("game")}>START SKIRMISH</button><p className="fine">This build simulates the second player with AI.</p></aside></section>}
 {screen==="game"&&<section className="game"><div className="resourceBar"><span>WOOD <b>420</b></span><span>FOOD <b>{food}</b></span><span>GOLD <b>{gold}</b></span><span>POPULATION <b>{pop}/30</b></span><button onClick={()=>setScreen("lobby")}>LEAVE MATCH</button></div><div className="battle"><canvas ref={canvasRef} width={960} height={640} onClick={click}/><div className="mission"><small>SKIRMISH OBJECTIVE</small><b>Destroy the Imperial fortress</b></div></div><div className="command"><div className="heroMini"><img src="/mawiyya.png" alt="Mawiyya"/><div><small>COMMANDER</small><b>QUEEN MAWIYYA</b><span>Desert cavalry move 15% faster</span></div></div><div className="orders">{(["spearman","archer","rider"] as const).map((k,i)=><button key={k} onClick={()=>train(k)}><b>{["⚔","➶","♞"][i]}</b><span>{k}<small>80F · 40G</small></span></button>)}<button onClick={()=>{setFood(v=>v+100);setGold(v=>v+75);setMessage("Caravan supplies received.")}}><b>✦</b><span>Supplies<small>DEMO</small></span></button></div><div className="log">{message}</div></div></section>}</main>}
function fort(c:CanvasRenderingContext2D,x:number,y:number,color:string){c.fillStyle="#32261f";c.beginPath();c.ellipse(x,y+30,70,32,0,0,7);c.fill();c.fillStyle=color;c.fillRect(x-43,y-25,86,55);c.fillStyle="#d5bd89";for(let i=-1;i<=1;i++)c.fillRect(x+i*31-9,y-43,18,22);c.fillStyle="#171411";c.fillRect(x-10,y+5,20,25)}
function tree(c:CanvasRenderingContext2D,x:number,y:number){c.fillStyle="#4b301e";c.fillRect(x-3,y,6,16);c.fillStyle="#314936";c.beginPath();c.arc(x,y,13,0,7);c.fill()}
function warrior(c:CanvasRenderingContext2D,u:Unit,s:boolean){const col=u.team==="player"?"#4fbfc5":"#c94339";if(s){c.strokeStyle="#f0d278";c.lineWidth=2;c.beginPath();c.ellipse(u.x,u.y+10,19,9,0,0,7);c.stroke()}c.fillStyle="#1c1714";c.beginPath();c.arc(u.x,u.y-7,6,0,7);c.fill();c.fillStyle=col;c.beginPath();c.moveTo(u.x,u.y-2);c.lineTo(u.x-10,u.y+17);c.lineTo(u.x+10,u.y+17);c.fill();c.strokeStyle="#ead8ad";c.lineWidth=2;c.beginPath();c.moveTo(u.x+4,u.y);c.lineTo(u.x+13,u.y-18);c.stroke();c.fillStyle="#151515";c.fillRect(u.x-14,u.y-24,28,3);c.fillStyle="#5bc96d";c.fillRect(u.x-14,u.y-24,28*u.hp/100,3)}
